Use shell_out instead of output_of_command for yum package provider
The yum package provider was broken by #2924 because
Chef::Mixin::Command was removed from the base Package provider.

Without this patch, I was getting:
```
    NoMethodError
    -------------
    undefined method `output_of_command' for #<Chef::Provider::Package::Yum:0x00000003a5f278>
```
when trying to execute

```ruby
package "gdb" do
  action :install
end
```

on Centos 6.5

Chef was breaking in weird ways and it didn't produce a stacktrace.out,
which was a little concerning, however that's a different bug