Use Mixlib::Shellout instead of Chef::Mixin::Command
Using C:\Users\Administrator>chef-solo -i 30 -s 5 -c C:/monsoon/solo.rb -j http://foo-bar/get-run -r http://foo-bar.com/cookbooks.tar.gz
failled with error : 
[2015-06-25T15:01:52+02:00] DEBUG: ---- End output of tar zxvf C:/chef/recipes.t
gz -C C:/chef ----
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:140:in `block in ou
tput_of_command': undefined method `exitstatus' for nil:NilClass (NoMethodError)

        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
 `chdir'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
 `output_of_command'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:101:in
 `run_command_and_return_stdout_stderr'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:79:in
`run_command'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/application/solo.rb:217
:in `reconfigure'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:58:in `r
un'
        from C:/opscode/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (requi
red)>'
        from C:/opscode/chef/bin/chef-solo:63:in `load'
        from C:/opscode/chef/bin/chef-solo:63:in `<main>'

using Mixlib::ShellOut instead of Chef::Mixin::Command solved the issue