Bump Ruby and friends so Ohai 8+ installs
Fixes this build error:

```
ERROR:  Error installing ohai-8.2.0.gem:
	ohai requires Ruby version >= 2.0.0.
```