Require chef/version when trying to read it
When a node is bootstrapped in FIPS mode and then tries to run a
chef-client run it gets the following error:

```
STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.18.31/lib/chef-config/workstation_config_loader.rb:163:in `rescue in apply_config': You have an error in your config file /var/opt/delivery/workspace/.chef/knife.rb (ChefConfig::ConfigurationError)

NameError: uninitialized constant Chef
  /var/opt/delivery/workspace/.chef/knife.rb:2:in `eval'
  /var/opt/delivery/workspace/.chef/knife.rb:2:in `eval'
  /var/opt/delivery/workspace/.chef/knife.rb:2:in `from_string'
```

Signed-off-by: tyler-ball <tyleraball@gmail.com>