Add support to cab_package for non-English system locales
When using cap_package on Windows with non-English system locales, such as Russian, chef-client throws up an error:
undefined method `[]' for nil:NilClass
The reason is that dism.exe output is in russian language and therefore cannot be parsed.
This PR ensures that output of dism.exe will be always in English.