Add missing requires to chef/policy_builder/dynamic
This was coming in for free before somehow, but now it's causing
failures in the Chef Workstation specs.

ERROR: Chef Infra failed to converge: uninitialized constant Chef::PolicyBuilder::Dynamic::ExpandNodeObject from file /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/policy_builder/dynamic.rb:158:in `select_implementation'
Caused by: (NameError) uninitialized constant Chef::PolicyBuilder::Dynamic::ExpandNodeObject

Signed-off-by: Tim Smith <tsmith@chef.io>