Adjust junglist recipe Made the runner report back its errors, instead of throwing a useless stack:
aj@junglist (branch: master) ~/chef$ sudo ./bin/chef-client -l info -c ./examples/config/chef-solo.rb
INFO: Starting Chef Run
ERROR: file[/tmp/glen] (/home/aj/git/chef/examples/config/cookbooks/tempfile/recipes/default.rb line 1) had an error:
./bin/../lib/chef/runner.rb:85:in `converge': undefined local variable or method `e' for #<Chef::Runner:0xb6bd5360> (NameError)
        from ./bin/../lib/chef/resource_collection.rb:59:in `each'
        from ./bin/../lib/chef/resource_collection.rb:58:in `each'
        from ./bin/../lib/chef/runner.rb:59:in `converge'
        from ./bin/../lib/chef/client.rb:141:in `converge'
        from ./bin/../lib/chef/client.rb:52:in `run'
        from ./bin/chef-client:65