fix: apt_repository gpg key import for newer APT versions
A normal `gpg --import` creates a GnuPG keybox database file, which, for
previous Debian versions, was not a problem for APT.

On newer Debian versions (e.g. 13/Trixie), however, APT uses `sqv` to
verify the keys, which seems not to be compatible with the GnuPG keybox
database file.

```
Sub-process /usr/bin/sqv returned an error code (1), error message is:
Error: Failed to parse keyring "/etc/apt/keyrings/om-debian.gpg"  Caused
by:     0: Reading "/etc/apt/keyrings/om-debian.gpg": EOF     1: EOF
```

The solution is to import to a `OpenPGP Public Key Version 4` ring file,
which does work.

https://github.com/chef/chef/pull/15218#issuecomment-3224592196

Signed-off-by: Frederik Thuysbaert <frederik.thuysbaert@combell.group>